Repository WaitDoc/WaitDoc, pull requests merged in 2023-07, with the labels that each got.

#50 noShow 처리 및 병원 관리자 허가기능 구현
  build.gradle
  src/main/generated/com/team13/WaitDoc/base/entity/QBaseEntity.java
  src/main/generated/com/team13/WaitDoc/blacklist/entity/QBlacklist.java
  src/main/generated/com/team13/WaitDoc/chats/entity/QInquiryMessage.java
  src/main/generated/com/team13/WaitDoc/hospital/entity/QHospital.java
  src/main/generated/com/team13/WaitDoc/hospital/entity/QHospitalInquiry.java
  src/main/generated/com/team13/WaitDoc/hospital/entity/QHospitalInquiryMember.java
  src/main/generated/com/team13/WaitDoc/hospital/entity/QHospitalMember.java
  src/main/generated/com/team13/WaitDoc/member/entity/QMember.java
  src/main/generated/com/team13/WaitDoc/waiting/entity/QWaiting.java
  src/main/java/com/team13/WaitDoc/admin/controller/AdminController.java
  src/main/java/com/team13/WaitDoc/base/initData/NotProd.java
  src/main/java/com/team13/WaitDoc/blacklist/entity/Blacklist.java
  src/main/java/com/team13/WaitDoc/blacklist/repository/BlacklistRepository.java
  src/main/java/com/team13/WaitDoc/blacklist/service/BlacklistService.java
  src/main/java/com/team13/WaitDoc/hospital/controller/HospitalController.java
  src/main/java/com/team13/WaitDoc/hospital/entity/HospitalMember.java
  src/main/java/com/team13/WaitDoc/hospital/entity/HospitalMemberRole.java
  src/main/java/com/team13/WaitDoc/hospital/repository/HospitalMemberRepository.java
  src/main/java/com/team13/WaitDoc/hospital/repository/HospitalRepository.java
  src/main/java/com/team13/WaitDoc/hospital/service/HospitalMemberService.java
  src/main/java/com/team13/WaitDoc/hospital/service/HospitalService.java
  src/main/java/com/team13/WaitDoc/member/service/MemberService.java
  src/main/java/com/team13/WaitDoc/waiting/controller/AdminController.java
  src/main/java/com/team13/WaitDoc/waiting/controller/WaitingAdminController.java
  src/main/java/com/team13/WaitDoc/waiting/controller/WaitingController.java
  src/main/java/com/team13/WaitDoc/waiting/dto/WaitingInfo.java
  src/main/resources/templates/admin/apply.html
  src/main/resources/templates/admin/waitinglist.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/hospital/detail.html
  src/main/resources/templates/waiting/waitingpage.html
Labels: enhancement

#60 1:1 채팅하기 연결 & 로그인 오류 해결 & ui 글씨체 적용
  build.gradle
  src/main/java/com/team13/WaitDoc/admin/controller/AdminController.java
  src/main/java/com/team13/WaitDoc/base/config/auth/CustomOAuth2UserService.java
  src/main/java/com/team13/WaitDoc/chats/controller/InquiryMessageController.java
  src/main/java/com/team13/WaitDoc/hospital/controller/AjaxHospitalInquiryController.java
  src/main/java/com/team13/WaitDoc/hospital/controller/HospitalController.java
  src/main/java/com/team13/WaitDoc/hospital/controller/HospitalInquiryController.java
  src/main/java/com/team13/WaitDoc/hospital/repository/HospitalDslRepositoryImpl.java
  src/main/java/com/team13/WaitDoc/hospital/service/HospitalInquiryService.java
  src/main/java/com/team13/WaitDoc/member/controller/MemberController.java
  src/main/java/com/team13/WaitDoc/security/SecurityUser.java
  src/main/resources/static/css/common.css
  src/main/resources/templates/chatting/hospitalInquiry/detail.html
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/index.html
  src/main/resources/templates/member/mypage.html
Labels: 🐞bug, enhancement

#63 마이페이지 , 채팅방 오류 해결
  src/main/java/com/team13/WaitDoc/chats/controller/InquiryMessageController.java
  src/main/java/com/team13/WaitDoc/member/controller/MemberController.java
  src/main/java/com/team13/WaitDoc/member/repository/MemberRepository.java
  src/main/java/com/team13/WaitDoc/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/static/js/InquiryMessage.js
  src/main/resources/templates/chatting/hospitalInquiry/detail.html
  src/main/resources/templates/index.html
  src/main/resources/templates/member/mypage.html
Labels: 🔨fix

#64 member 데이터가 초기화되지 않는 문제해결
  src/main/generated/com/team13/WaitDoc/member/entity/QMember.java
  src/main/java/com/team13/WaitDoc/blacklist/entity/Blacklist.java
  src/main/java/com/team13/WaitDoc/member/entity/Member.java
Labels: 🔨fix

#84 서류 보관,등록 & 회원 정보 수정, 조회 로직 구현&메인페이지 생성
  build.gradle
  src/main/java/com/team13/WaitDoc/WaitDocApplication.java
  src/main/java/com/team13/WaitDoc/base/config/auth/SecurityConfig.java
  src/main/java/com/team13/WaitDoc/category/DTO/CategoryRequestDTO.java
  src/main/java/com/team13/WaitDoc/hospital/controller/HospitalController.java
  src/main/java/com/team13/WaitDoc/member/controller/MemberController.java
  src/main/java/com/team13/WaitDoc/member/entity/Member.java
  src/main/java/com/team13/WaitDoc/member/service/MemberService.java
  src/main/java/com/team13/WaitDoc/paper/controller/PaperController.java
  src/main/java/com/team13/WaitDoc/paper/dto/PaperDto.java
  src/main/java/com/team13/WaitDoc/paper/entity/Paper.java
  src/main/java/com/team13/WaitDoc/paper/repository/PaperRepository.java
  src/main/java/com/team13/WaitDoc/paper/service/PaperService.java
  src/main/java/com/team13/WaitDoc/s3/config/AmazonS3Config.java
  src/main/java/com/team13/WaitDoc/s3/properties/AmazonS3Properties.java
  src/main/java/com/team13/WaitDoc/s3/repository/AmazonS3Repository.java
  src/main/java/com/team13/WaitDoc/s3/service/AmazonS3Service.java
  src/main/java/com/team13/WaitDoc/utils/MimeTypeUtils.java
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/index.html
  src/main/resources/templates/main.html
  src/main/resources/templates/member/mypage.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/paper/paperDetail.html
  src/main/resources/templates/paper/paperList.html
  src/main/resources/templates/paper/paperRegister.html
  src/test/java/com/team13/WaitDoc/WaitDocApplicationTests.java
Labels: 🐞bug, enhancement

#106 병원 관리자용 문의리스트 - 마이페이지 연결
  src/main/java/com/team13/WaitDoc/hospital/controller/HospitalController.java
  src/main/java/com/team13/WaitDoc/hospital/entity/HospitalMemberRole.java
  src/main/java/com/team13/WaitDoc/hospital/service/HospitalMemberService.java
  src/main/java/com/team13/WaitDoc/member/controller/MemberController.java
  src/main/java/com/team13/WaitDoc/member/entity/Member.java
  src/main/resources/templates/member/mypage.html
Labels: 🐞bug
