Repository WaitDoc/WaitDoc, pull requests merged in 2023-06, with the labels that each got.

#10 멤버 엔티티 & Secutiry Config 설정
  build.gradle
  src/main/java/com/team13/WaitDoc/base/config/SecurityConfig.java
  src/main/java/com/team13/WaitDoc/member/entity/Member.java
  src/main/java/com/team13/WaitDoc/member/entity/MemberRole.java
Labels: enhancement

#14 Oauth 로그인 구현
  build.gradle
  src/main/java/com/team13/WaitDoc/base/config/auth/CustomOAuth2UserService.java
  src/main/java/com/team13/WaitDoc/base/config/auth/SecurityConfig.java
  src/main/java/com/team13/WaitDoc/member/controller/MemberController.java
  src/main/java/com/team13/WaitDoc/member/entity/Member.java
  src/main/java/com/team13/WaitDoc/member/repository/MemberRepository.java
  src/main/java/com/team13/WaitDoc/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/templates/member/login.html
Labels: 🚀feature

#18 Oauth 로그인 기능 고도화
  src/main/java/com/team13/WaitDoc/base/config/auth/CustomOAuth2UserService.java
  src/main/java/com/team13/WaitDoc/base/config/auth/OAuthAttributes.java
  src/main/java/com/team13/WaitDoc/base/config/auth/SecurityConfig.java
  src/main/java/com/team13/WaitDoc/base/config/auth/SessionMember.java
  src/main/java/com/team13/WaitDoc/member/entity/Member.java
  src/main/java/com/team13/WaitDoc/member/entity/MemberRole.java
  src/main/java/com/team13/WaitDoc/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 🚀feature, 🔥refactor

#20 네이버, 구글 로그인 구현
  src/main/java/com/team13/WaitDoc/base/config/auth/OAuthAttributes.java
  src/main/resources/application.yml
  src/main/resources/templates/member/login.html
Labels: 🚀feature

#30 waiting 도메인 및 코드 복구
  build.gradle
  src/main/java/com/team13/WaitDoc/base/config/auth/SessionMember.java
  src/main/java/com/team13/WaitDoc/base/initData/ApiData.java
  src/main/java/com/team13/WaitDoc/hospital/service/HospitalService.java
  src/main/java/com/team13/WaitDoc/kafka/consumer/KafkaConsumerService.java
  src/main/java/com/team13/WaitDoc/kafka/producer/KafkaProducerConfig.java
  src/main/java/com/team13/WaitDoc/kafka/producer/KafkaProducerService.java
  src/main/java/com/team13/WaitDoc/member/service/MemberService.java
  src/main/java/com/team13/WaitDoc/waiting/controller/WaitingController.java
  src/main/java/com/team13/WaitDoc/waiting/dto/WaitingRequest.java
  src/main/java/com/team13/WaitDoc/waiting/entity/Waiting.java
  src/main/java/com/team13/WaitDoc/waiting/repository/WaitingRepository.java
  src/main/java/com/team13/WaitDoc/waiting/service/WaitingService.java
  src/main/resources/application.yml
  src/main/resources/templates/waiting/waitingpage.html
Labels: 🔨fix

#39 병원 관리자 페이지 및 줄서기 관리 기능 구현
  src/main/java/com/team13/WaitDoc/kafka/consumer/KafkaConsumerConfig.java
  src/main/java/com/team13/WaitDoc/kafka/consumer/KafkaConsumerService.java
  src/main/java/com/team13/WaitDoc/waiting/controller/AdminController.java
  src/main/java/com/team13/WaitDoc/waiting/controller/WaitingController.java
  src/main/java/com/team13/WaitDoc/waiting/dto/WaitingInfo.java
  src/main/java/com/team13/WaitDoc/waiting/repository/WaitingRepository.java
  src/main/java/com/team13/WaitDoc/waiting/service/WaitingService.java
  src/main/resources/templates/admin/waitinglist.html
  src/main/resources/templates/waiting/waitingpage.html
Labels: enhancement

#40 메인 프론트 작업
  src/main/resources/templates/common/layout.html
  src/main/resources/templates/index.html
Labels: enhancement
